
version: "3.7"

services:
  server-1: &server
    image: "mysql/mysql-server:${MYSQL_VERSION}"
    container_name: "server-1"
    hostname: "server-1"
    # user: $UID:$GID
    ports:
      - "30001:3306"
      - "40001:33060"
    command:
      - "--server_id=1"
    environment:
      - MYSQL_ROOT_PASSWORD
      - MYSQL_ROOT_HOST
    volumes:
      - "./my.cnf:/etc/my.cnf"
      - "./data/server-1:/var/lib/mysql"
    restart: always

  server-2:
    <<: *server
    container_name: "server-2"
    hostname: "server-2"
    ports:
      - "30002:3306"
      - "40002:33060"
    command:
      - "--server_id=2"
    volumes:
      - "./my.cnf:/etc/my.cnf"
      - "./data/server-2:/var/lib/mysql"

  server-3:
    <<: *server
    container_name: "server-3"
    hostname: "server-3"
    ports:
      - "30003:3306"
      - "40003:33060"
    command:
      - "--server_id=3"
    volumes:
      - "./my.cnf:/etc/my.cnf"
      - "./data/server-3:/var/lib/mysql"

  shell:
    image: "mysql/mysql-server:${MYSQL_VERSION}"
    container_name: "shell"
    hostname: "shell"
    # user: $UID:$GID
    entrypoint: "/bin/shell-entrypoint"
    environment: &other-environment
      - MYSQL_USER
      - MYSQL_PASSWORD
      - MYSQL_HOST
      - MYSQL_PORT
      - MYSQL_CLUSTER_NAME
      - MYSQL_CLUSTER_OPTIONS
      - MYSQL_INNODB_NUM_MEMBERS
    volumes:
      - "./shell-entrypoint.sh:/bin/shell-entrypoint"
    depends_on: &other-depends
      - server-1
      - server-2
      - server-3

  router:
    image: "mysql/mysql-router:${MYSQL_VERSION}"
    container_name: "router"
    hostname: "router"
    # user: $UID:$GID
    ports:
      - "6446:6446"
      - "6447:6447"
    environment: *other-environment
    volumes:
      - "./data/router:/var/lib/mysqlrouter"
    depends_on: *other-depends
    restart: always

  prometheus-exporter:
    image: "prom/mysqld-exporter"
    container_name: "server-exporter"
    hostname: "server-exporter"
    profiles: [exporter]
    ports:
      - "9104:9104"
    environment:
      DATA_SOURCE_NAME: "${MYSQL_USER}:${MYSQL_PASSWORD}@(${MYSQL_HOST}:${MYSQL_PORT})/"
    depends_on: *other-depends
    restart: always

  phpmysqladmin:
    image: phpmyadmin:5.1.0
    hostname: "server-phpmysqladmin"
    container_name: "server-phpmysqladmin"
    profiles: [webtool]
    environment:
      - PMA_HOSTS=router:6446, router:6447, server-1, server-2, server-3
      - PMA_user=root
      - PMA_PASSWORD=mysql
      - UPLOAD_LIMIT=10M
    ports:
      - "3305:80"

